### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by pinkfloydFR** [Aadityajoshi151/Elysian#54] opened 2024-11-27 09:07 UTC
When i try to upload my bookmarks from latest brave version , got this error 👍 
```
PayloadTooLargeError: request entity too large
    at readStream (/Elysian/node_modules/raw-body/index.js:163:17)
    at getRawBody (/Elysian/node_modules/raw-body/index.js:116:12)
    at read (/Elysian/node_modules/body-parser/lib/read.js:79:3)
    at jsonParser (/Elysian/node_modules/body-parser/lib/types/json.js:138:5)
    at Layer.handle [as handle_request] (/Elysian/node_modules/express/lib/router/layer.js:95:5)
    at next (/Elysian/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/Elysian/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/Elysian/node_modules/express/lib/router/layer.js:95:5)
    at /Elysian/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/Elysian/node_modules/express/lib/router/index.js:346:12)
```

Config : 
```
services:
  elysian:
    image: aadityajoshi151/elysian:latest
    container_name: elysian
    privileged: true
    environment:
      - API_KEY=*****
      - PUID=1042
      - PGID=1042
      - TZ=Europe/Paris
#    ports:
#      - 6161:6161
    volumes:
      - ./data:/Elysian/src/data
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.elysian.rule=Host(`link.***.com`)
      - traefik.http.routers.elysian.entrypoints=websecure
      - traefik.http.routers.elysian.service=elysian
      - traefik.http.routers.elysian.tls=true
      - traefik.http.routers.elysian.middlewares=my-geoblock@file,sslheader@docker
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.services.elysian.loadbalancer.server.port=6161
    networks:
      elysian:
      traefik:

networks:
  elysian:
    name: elysian
    driver_opts:
      com.docker.network.bridge.name: br-elysian
  traefik:
    external: true

```

data  folder is empty fyi.

Thanks !

**Comment by Aadityajoshi151** [comment] 2024-11-27 12:22
Hi @pinkfloydFR 
Thank you for opening the issue.
It looks like the size of the request body exceeds the default limit of `express.json()` that I am using to parse the request body.
I was able to reproduce the issue on my end also by sending a lot of bookmarks (450 to be exact).
It should be solvable by increasing the default limit.
I will push a change soon. Meanwhile, could you provide me answers to following questions which might help me better understand the issue:
1. _When did you encounter the error?_ I am assuming after the initial install and config, when you first exported the bookmarks from the extension, you encountered this.
2. _How many bookmarks are you exporting?_ An approximate number should suffice.

**Comment by pinkfloydFR** [comment] 2024-11-27 16:03
Hi @Aadityajoshi151  !

1 : All right, just intalled the extension and the first try is getting the ( as the other try of course )

2 : All right again, i havec exactly 523 bookmarks ( i am not messy, all is organized in sub folder ;)   ) 👍 

![image](https://github.com/user-attachments/assets/4da0b490-1408-4f6b-a053-34903344c8b9)

Thanks for the update !

**Comment by Aadityajoshi151** [comment] 2024-11-28 13:20
Hi @pinkfloydFR 
I have pushed the change in the latest docker image. The issue was auto closed on merging the PR but I have re-opened it to hear back from you.
You can pull the latest image and try running it again. Make sure to remove the existing Elysian image beforehand to avoid any confusion.
Please let me know the status and then I'll close the issue.
Thank you.

**Comment by pinkfloydFR** [comment] 2024-11-28 14:06
Hi, 

For now all seem good, but... i am curently spammed with notification of export or moved bookbark...

As i have a big number of bookmark, i leave my browser as it for now, seeing if it's a feature or a bug :)    

The docker log show me this  :   

```
2024-11-28T14:07:35.647875000Z handleExportToElysian: Export successful
2024-11-28T14:07:36.061903000Z handleExportToElysian: Export successful
2024-11-28T14:07:36.270495000Z handleExportToElysian: Export successful
2024-11-28T14:07:53.933599000Z handleExportToElysian: Export successful
2024-11-28T14:08:06.568610000Z handleExportToElysian: Export successful
2024-11-28T14:08:07.069153000Z handleExportToElysian: Export successful
2024-11-28T14:08:07.262136000Z handleExportToElysian: Export successful
2024-11-28T14:08:37.720123000Z handleExportToElysian: Export successful
2024-11-28T14:08:38.080857000Z handleExportToElysian: Export successful
2024-11-28T14:08:38.272876000Z handleExportToElysian: Export successful
2024-11-28T14:09:08.579745000Z handleExportToElysian: Export successful
2024-11-28T14:09:38.853249000Z handleExportToElysian: Export successful
2024-11-28T14:09:39.246180000Z handleExportToElysian: Export successful
2024-11-28T14:09:39.453103000Z handleExportToElysian: Export successful
2024-11-28T14:10:09.839114000Z handleExportToElysian: Export successful
2024-11-28T14:10:40.104092000Z handleExportToElysian: Export successful
2024-11-28T14:10:40.533514000Z handleExportToElysian: Export successful
2024-11-28T14:10:40.753864000Z handleExportToElysian: Export successful
2024-11-28T14:10:56.204073000Z handleExportToElysian: Export successful
2024-11-28T14:10:56.936999000Z handleExportToElysian: Export successful
2024-11-28T14:11:11.090573000Z handleExportToElysian: Export successful
2024-11-28T14:11:11.645143000Z handleExportToElysian: Export successful
2024-11-28T14:11:11.842566000Z handleExportToElysian: Export successful
2024-11-28T14:11:42.130494000Z handleExportToElysian: Export successful
2024-11-28T14:12:12.321400000Z handleExportToElysian: Export successful
2024-11-28T14:12:42.524879000Z handleExportToElysian: Export successful
2024-11-28T14:13:00.816002000Z handleExportToElysian: Export successful
2024-11-28T14:13:12.743227000Z handleExportToElysian: Export successful
2024-11-28T14:13:13.228078000Z handleExportToElysian: Export successful
2024-11-28T14:13:13.423422000Z handleExportToElysian: Export successful
2024-11-28T14:13:16.296373000Z handleExportToElysian: Export successful
2024-11-28T14:13:31.770394000Z handleExportToElysian: Export successful
2024-11-28T14:13:43.717004000Z handleExportToElysian: Export successful
2024-11-28T14:13:44.211233000Z handleExportToElysian: Export successful
2024-11-28T14:13:44.417965000Z handleExportToElysian: Export successful
2024-11-28T14:13:47.245680000Z handleExportToElysian: Export successful
2024-11-28T14:14:02.727621000Z handleExportToElysian: Export successful
2024-11-28T14:14:14.714708000Z handleExportToElysian: Export successful
2024-11-28T14:14:15.192831000Z handleExportToElysian: Export successful
2024-11-28T14:14:15.416473000Z handleExportToElysian: Export successful
2024-11-28T14:14:18.238579000Z handleExportToElysian: Export successful
2024-11-28T14:14:33.720698000Z handleExportToElysian: Export successful
2024-11-28T14:14:45.688392000Z handleExportToElysian: Export successful
2024-11-28T14:14:46.137963000Z handleExportToElysian: Export successful
2024-11-28T14:14:46.345469000Z handleExportToElysian: Export successful
2024-11-28T14:14:49.192007000Z handleExportToElysian: Export successful
2024-11-28T14:15:04.661848000Z handleExportToElysian: Export successful
2024-11-28T14:15:16.600072000Z handleExportToElysian: Export successful
2024-11-28T14:15:17.075405000Z handleExportToElysian: Export successful
2024-11-28T14:15:17.280353000Z handleExportToElysian: Export successful
2024-11-28T14:15:47.709288000Z handleExportToElysian: Export successful
2024-11-28T14:15:48.082225000Z handleExportToElysian: Export successful
2024-11-28T14:15:48.283310000Z handleExportToElysian: Export successful
2024-11-28T14:15:53.560015000Z handleExportToElysian: Export successful
2024-11-28T14:16:09.052976000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.685074000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.691387000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.708289000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.722850000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.731130000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.737324000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.743741000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.748847000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.754391000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.759611000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.765461000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.771573000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.778243000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.783782000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.790024000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.795330000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.801162000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.806399000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.812233000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.817839000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.823391000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.828708000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.834579000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.839876000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.845923000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.851481000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.857787000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.863065000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.869256000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.874511000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.880669000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.885906000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.892336000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.897494000Z handleExportToElysian: Export successful
2024-11-28T14:16:18.943476000Z handleExportToElysian: Export successful
2024-11-28T14:16:49.029015000Z handleExportToElysian: Export successful
2024-11-28T14:17:19.350946000Z handleExportToElysian: Export successful
2024-11-28T14:17:49.543248000Z handleExportToElysian: Export successful
2024-11-28T14:18:14.515215000Z handleExportToElysian: Export successful
2024-11-28T14:18:19.735581000Z handleExportToElysian: Export successful
2024-11-28T14:18:19.947849000Z handleExportToElysian: Export successful
2024-11-28T14:18:50.255611000Z handleExportToElysian: Export successful
2024-11-28T14:19:12.330486000Z handleExportToElysian: Export successful
2024-11-28T14:19:20.453847000Z handleExportToElysian: Export successful
2024-11-28T14:19:20.659314000Z handleExportToElysian: Export successful`
```

UPDATE : 
seem a bug for me....

![Animation](https://github.com/user-attachments/assets/e1835388-ed76-4a82-b940-8e0d436ef2d8)

**Comment by Aadityajoshi151** [comment] 2024-11-28 16:33
Hi @pinkfloydFR 
This is a weird one. I tested by exporting 3000 bookmarks on latest version of brave and it works fine for me. Only 1 notification is received for the entire export and only 1 log statement is observed in docker logs also.
The move action also behaves the same way and both of these actions are completed instantly.
In your case, it looks like it is getting stuck in an infinite loop (sort of).
I'd suggest you do a fresh setup once, both on server side and browser side by re-installing the extension.
If the issue still persists, you can open a new issue with the same logs and images. Also please provide detailed steps in the new issue as it will help me in reproducing the issue on my end.
I am closing this as the issue regarding the `PayloadTooLargeError: request entity too large` seems to be fixed.
Thanks.

**Closed by Aadityajoshi151** 2024-11-28 16:33 UTC
Labels: bug
